-- ═══════════════════════════════════════════════════════════════════════════
--  AniSense starter data  (run after schema.sql)
--
--  GENERATED by scripts/build-seed.mjs from the app's own crop data. To change
--  it, edit src/data/crops.ts, run  node scripts/build-seed.mjs , and run this
--  file again. Safe to re-run: every row is added or brought up to date.
--
--  10 crop groups · 24 varieties · 24 prices for today · 6 badges
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Crop groups ─────────────────────────────────────────────────────────────
insert into public.crop_groups (id, name, family, days_to_harvest, sort_order) values
  ('rice', 'Rice', 'Crops', 110, 1),
  ('corn', 'Corn', 'Crops', 105, 2),
  ('onions', 'Onions', 'Vegetables', 100, 3),
  ('garlic', 'Garlic', 'Vegetables', 120, 4),
  ('tomatoes', 'Tomatoes', 'Vegetables', 75, 5),
  ('squash', 'Squash', 'Vegetables', 90, 6),
  ('ampalaya', 'Ampalaya', 'Vegetables', null, 7),
  ('calamansi', 'Calamansi', 'Fruits', null, 8),
  ('mango', 'Mango', 'Fruits', null, 9),
  ('watermelon', 'Watermelon', 'Fruits', null, 10)
on conflict (id) do update set
  name = excluded.name, family = excluded.family,
  days_to_harvest = excluded.days_to_harvest, sort_order = excluded.sort_order;

-- ─── Varieties ───────────────────────────────────────────────────────────────
insert into public.crops (id, group_id, name, sort_order) values
  ('rice-special', 'rice', 'Special Rice', 1),
  ('rice-well-milled', 'rice', 'Well Milled', 2),
  ('rice-regular-milled', 'rice', 'Regular Milled', 3),
  ('onion-red', 'onions', 'Red Onion', 4),
  ('onion-white', 'onions', 'Yellow/White Onion', 5),
  ('onion-yellow', 'onions', 'Shallots Onion', 6),
  ('onion-spring', 'onions', 'Spring Onion', 7),
  ('cala-regular', 'calamansi', 'Regular Calamansi', 8),
  ('mango-carab', 'mango', 'Carabao Mango', 9),
  ('mango-indian', 'mango', 'Indian Mango', 10),
  ('mango-horse', 'mango', 'Horse Mango', 11),
  ('mango-pahutan', 'mango', 'Pahutan', 12),
  ('garlic-native', 'garlic', 'Native Garlic', 13),
  ('tom-cherry', 'tomatoes', 'Diamante Max F1 Tomato', 14),
  ('tom-roma', 'tomatoes', 'Platinum F1 Tomato', 15),
  ('tom-beef', 'tomatoes', 'Assila F1 Tomato', 16),
  ('corn-yellow', 'corn', 'Yellow Corn', 17),
  ('corn-white', 'corn', 'White Corn', 18),
  ('corn-sweet', 'corn', 'Sweet Corn', 19),
  ('ampalaya-native', 'ampalaya', 'Native Ampalaya', 20),
  ('ampalaya-galaxy', 'ampalaya', 'Galaxy Ampalaya', 21),
  ('melon-sweet', 'watermelon', 'Sweet Watermelon', 22),
  ('melon-seedless', 'watermelon', 'Seedless Watermelon', 23),
  ('squash-kalabasa', 'squash', 'Kalabasa', 24)
on conflict (id) do update set
  group_id = excluded.group_id, name = excluded.name, sort_order = excluded.sort_order;

-- ─── Today's prices ──────────────────────────────────────────────────────────
-- One row per variety for today. The admin adds a new day's prices the same
-- way (or in Table Editor → crop_prices); the app always shows the newest.
insert into public.crop_prices (crop_id, price_date, price_per_kg, change_pct) values
  ('rice-special', current_date, 65, 2.5),
  ('rice-well-milled', current_date, 52, 1.8),
  ('rice-regular-milled', current_date, 42, 0.2),
  ('onion-red', current_date, 45, -0.8),
  ('onion-white', current_date, 38, 1.2),
  ('onion-yellow', current_date, 35, 0.5),
  ('onion-spring', current_date, 20, -1),
  ('cala-regular', current_date, 160, 1.8),
  ('mango-carab', current_date, 80, 3.5),
  ('mango-indian', current_date, 40, 1),
  ('mango-horse', current_date, 25, -0.5),
  ('mango-pahutan', current_date, 35, 2),
  ('garlic-native', current_date, 150, 1.2),
  ('tom-cherry', current_date, 25, 3.2),
  ('tom-roma', current_date, 15, 2),
  ('tom-beef', current_date, 20, -0.5),
  ('corn-yellow', current_date, 70, 1.5),
  ('corn-white', current_date, 65, 1),
  ('corn-sweet', current_date, 30, 2.5),
  ('ampalaya-native', current_date, 60, 2.2),
  ('ampalaya-galaxy', current_date, 55, -0.8),
  ('melon-sweet', current_date, 28, 1.4),
  ('melon-seedless', current_date, 35, 0.6),
  ('squash-kalabasa', current_date, 12, -1.3)
on conflict (crop_id, price_date) do update set
  price_per_kg = excluded.price_per_kg, change_pct = excluded.change_pct;

-- ─── Badges ──────────────────────────────────────────────────────────────────
insert into public.achievements (id, name, description, awarded_by, sort_order) values
  ('newbie', 'Newbie', 'Joined AniSense.', 'auto', 1),
  ('first-harvest', 'First harvest', 'Posted a first harvest in the Market.', 'auto', 2),
  ('first-sale', 'First sale', 'Made or recorded a first sale.', 'auto', 3),
  ('farmer-of-the-week', 'AniSense Farmer of the Week', 'Featured to buyers as one of the week''s best-rated farmers.', 'auto', 4),
  ('farmer-of-the-month', 'AniSense Farmer of the Month', 'Top ratings and the most sales in a month.', 'admin', 5),
  ('farmer-of-the-year', 'AniSense Farmer of the Year', 'AniSense''s top farmer of the whole year.', 'admin', 6)
on conflict (id) do update set
  name = excluded.name, description = excluded.description,
  awarded_by = excluded.awarded_by, sort_order = excluded.sort_order;
