// ─── node scripts/build-prices.mjs ────────────────────────────────────────────
// Writes src/data/priceHistory.ts from data/historical-prices.csv, the price
// records the study is built on (retail prices): one row per month, one column per variety
// (named by the app's crop id), an empty cell where nothing was recorded.
//
// The app bundles the result, so the prices and their history show without a
// signal. Run it again after adding a month to the CSV, then:
//
//   ml/.venv/Scripts/python ml/train_forecasts.py   the forecasts
//   node scripts/build-seed.mjs                     the database's copy

import { readFileSync, writeFileSync } from "node:fs";

const CSV = "data/historical-prices.csv";
const OUT = "src/data/priceHistory.ts";

const lines = readFileSync(CSV, "utf8").split(/\r?\n/).filter(l => l.trim());
const [head, ...rows] = lines.map(l => l.split(",").map(c => c.trim()));
if (head[0] !== "month") throw new Error(`${CSV}: the first column must be "month"`);
const ids = head.slice(1);

const months = [];
const series = Object.fromEntries(ids.map(id => [id, []]));
for (const [month, ...cells] of rows) {
  if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) throw new Error(`${CSV}: "${month}" is not a month like 2026-09`);
  if (months.length && month <= months[months.length - 1]) throw new Error(`${CSV}: ${month} is out of order`);
  if (cells.length !== ids.length) throw new Error(`${CSV}: ${month} has ${cells.length} prices, expected ${ids.length}`);
  months.push(month);
  cells.forEach((c, i) => {
    const price = c === "" ? null : Number(c);
    if (price !== null && !(price > 0)) throw new Error(`${CSV}: ${month} ${ids[i]} "${c}" is not a price`);
    series[ids[i]].push(price);
  });
}
for (const id of ids) {
  if (series[id].every(p => p === null)) throw new Error(`${CSV}: ${id} has no prices`);
}

const row = (id) => `  ${JSON.stringify(id)}: [${series[id].map(p => (p === null ? "null" : p)).join(", ")}],`;
const ts = `// GENERATED by scripts/build-prices.mjs from ${CSV}.
// Edit that file, not this one, then run  node scripts/build-prices.mjs .

// ─── Price records ────────────────────────────────────────────────────────────
// Monthly retail prices per kilo for the crops the study covers, ${months[0]} to
// ${months[months.length - 1]}. \`null\` is a month with no record.

/** Every month on record, oldest first: "2021-01". */
export const PRICE_MONTHS: string[] = ${JSON.stringify(months)};

/** Crop id → its price in each of PRICE_MONTHS, in the same order. */
export const PRICE_SERIES: Record<string, (number | null)[]> = {
${ids.map(row).join("\n")}
};
`;
writeFileSync(OUT, ts);
const recorded = ids.reduce((n, id) => n + series[id].filter(p => p !== null).length, 0);
console.log(`${OUT}: ${ids.length} varieties, ${months.length} months (${months[0]} to ${months[months.length - 1]}), ${recorded} prices`);
