// ─── node scripts/build-privacy.mjs ───────────────────────────────────────────
// Writes docs/privacy-policy.html, the page Google Play's listing links to,
// from the same text the app shows (src/data/privacyPolicy.ts), so the web
// page and the app can never say different things.
//
// Run it again after editing the policy. The page is self-contained: both
// languages are in it, with a switch; with scripts off, English shows first
// and Tagalog after it.

import { build } from "esbuild";
import { writeFileSync } from "node:fs";

const out = await build({
  stdin: { contents: `export * from "./src/data/privacyPolicy";`, resolveDir: process.cwd(), loader: "ts" },
  bundle: true, format: "esm", platform: "node", write: false, logLevel: "error",
});
const { PRIVACY, fillPrivacy } = await import("data:text/javascript;base64," + Buffer.from(out.outputFiles[0].text).toString("base64"));

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
// The support address is a link wherever it appears.
const text = (s) => esc(fillPrivacy(s)).split(PRIVACY.email).join(`<a href="mailto:${PRIVACY.email}">${PRIVACY.email}</a>`);
const date = (lang) => new Date(`${PRIVACY.effective}T00:00:00`)
  .toLocaleDateString(lang === "tl" ? "fil-PH" : "en-PH", { year: "numeric", month: "long", day: "numeric" });

const body = (lang) => `
    <div class="doc" data-doc="${lang}" lang="${lang === "tl" ? "fil" : "en"}">
      <h1>${esc(PRIVACY.title[lang])}</h1>
      <p class="date">${esc(PRIVACY.effectiveLabel[lang].replace("{date}", date(lang)))}</p>
${PRIVACY.sections.map((s, i) => `      <section id="${lang}-${s.id}"${i === 0 ? ' class="summary"' : ""}>
        <h2>${i === 0 ? "" : `<span class="num">${i}.</span> `}${esc(s.title[lang])}</h2>
${s.body.map(b => b.p
  ? `        <p${b.p[lang].endsWith(":") ? ' class="sub"' : ""}>${text(b.p[lang])}</p>`
  : `        <ul>\n${b.list[lang].map(li => `          <li>${text(li)}</li>`).join("\n")}\n        </ul>`).join("\n")}
      </section>`).join("\n")}
      <p class="foot"><a href="delete-account.html">${lang === "tl" ? "Paano burahin ang account mo" : "How to delete your account"}</a></p>
    </div>`;

const html = `<!doctype html>
<!-- Generated by scripts/build-privacy.mjs from src/data/privacyPolicy.ts. Edit that file, not this one. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AniSense ${esc(PRIVACY.title.en)}</title>
  <meta name="description" content="What AniSense collects, why, who can see it, and your rights under the Data Privacy Act.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@500;600;700&family=Source+Sans+3:wght@400;600&display=swap" rel="stylesheet">
  <style>
    :root { --ink: #16211B; --paper: #F2F3F4; --card: #fff; --tanim: #0B6B41; --muted: #474B4F; --faint: #606469; }
    * { box-sizing: border-box; margin: 0; }
    body { background: var(--paper); color: #2F3336; font: 17px/1.6 "Source Sans 3", system-ui, sans-serif; -webkit-font-smoothing: antialiased; }
    main { max-width: 680px; margin: 0 auto; padding: 28px 20px 56px; }
    header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 22px; }
    .brand { font: 700 20px Lexend, sans-serif; letter-spacing: -.01em; color: var(--ink); }
    .lang { display: flex; padding: 3px; border-radius: 12px; background: rgba(118,118,128,.13); }
    .lang button { min-height: 40px; padding: 0 14px; border: 0; border-radius: 9px; background: none; font: 600 16px Lexend, sans-serif; color: var(--muted); cursor: pointer; }
    .lang button[aria-pressed="true"] { background: var(--card); color: var(--ink); box-shadow: 0 1px 3px rgba(0,0,0,.14); }
    .doc { background: var(--card); border-radius: 22px; padding: 26px 24px 30px; margin-bottom: 18px;
           box-shadow: 0 0 0 1px rgba(22,33,27,.05), 0 1px 2px rgba(22,33,27,.06), 0 14px 30px -20px rgba(22,33,27,.3); }
    h1 { font: 700 30px/1.15 Lexend, sans-serif; letter-spacing: -.02em; color: var(--ink); }
    .date { margin-top: 8px; font-size: 16px; font-weight: 600; color: var(--faint); }
    section { margin-top: 26px; padding-top: 24px; border-top: 1px solid #D9DBDE; }
    section.summary { margin-top: 16px; padding: 16px 18px 18px; border: 0; border-left: 3px solid var(--tanim); border-radius: 14px; background: #F3F9F5; }
    section.summary + section { border-top: 0; padding-top: 4px; }
    h2 { font: 700 20px/1.3 Lexend, sans-serif; letter-spacing: -.012em; color: var(--ink); margin-bottom: 10px; }
    .num { color: var(--tanim); }
    p + p, ul + p, p + ul, ul + ul { margin-top: 12px; }
    p.sub { font-weight: 600; color: var(--ink); margin-top: 18px; }
    h2 + p.sub { margin-top: 0; }
    p.sub + ul { margin-top: 8px; }
    ul { padding-left: 22px; }
    li + li { margin-top: 8px; }
    li::marker { color: var(--faint); }
    a { color: var(--tanim); font-weight: 600; overflow-wrap: anywhere; }
    .foot { margin-top: 28px; padding-top: 18px; border-top: 1px solid #D9DBDE; }
    /* With scripts on, one language at a time. */
    .js .doc[hidden] { display: none; }
  </style>
</head>
<body>
<main>
  <header>
    <div class="brand">AniSense</div>
    <div class="lang" role="group" aria-label="Language">
      <button type="button" data-lang="en" aria-pressed="true">English</button>
      <button type="button" data-lang="tl" aria-pressed="false">Tagalog</button>
    </div>
  </header>
${body("en")}
${body("tl")}
</main>
<script>
  // Tagalog first for a phone set to Filipino; the switch works either way.
  document.documentElement.classList.add("js");
  var lang = /^(tl|fil)/i.test(navigator.language || "") ? "tl" : "en";
  function show(l) {
    lang = l;
    document.querySelectorAll("[data-doc]").forEach(function (d) { d.hidden = d.dataset.doc !== l; });
    document.querySelectorAll("[data-lang]").forEach(function (b) { b.setAttribute("aria-pressed", String(b.dataset.lang === l)); });
    document.documentElement.lang = l === "tl" ? "fil" : "en";
  }
  document.querySelectorAll("[data-lang]").forEach(function (b) { b.onclick = function () { show(b.dataset.lang); }; });
  show(lang);
</script>
</body>
</html>
`;

writeFileSync("docs/privacy-policy.html", html);
console.log(`docs/privacy-policy.html written: ${PRIVACY.sections.length} sections, in effect from ${PRIVACY.effective}.`);
