// ─── node scripts/build-seed.mjs ──────────────────────────────────────────────
// Writes supabase/seed.sql from the app's own data, so the database and the
// app can never drift apart:
//
//   crop_groups     the 10 crop types (src/data/crops.ts FAMILY_GROUPS, with
//                   days to harvest from src/data/cropCycles.ts)
//   crops           every variety (RICE_VARIETIES + CROP_GROUPS)
//   crop_prices     the price records: every month on record for the study's
//                   varieties (src/data/generated/priceHistory.ts, built from
//                   data/historical-prices.csv), and one sample price for
//                   each variety that has no records yet
//   crop_forecasts  the next months, per variety and model
//                   (src/data/generated/forecasts.json, from ml/train_forecasts.py)
//   achievements    the badges
//
// Run it again after changing the crop data, adding a month of prices or
// training the models again, then run seed.sql again in the SQL editor. Safe
// to re-run: every insert updates what is already there.

import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";

// Load the app's TypeScript data files as a module.
const out = await build({
  stdin: {
    contents: `export { RICE_VARIETIES, CROP_GROUPS, FAMILY_GROUPS } from "./src/data/crops";
               export { CROP_CYCLES } from "./src/data/cropCycles";
               export { PRICE_MONTHS, PRICE_SERIES } from "./src/data/generated/priceHistory";`,
    resolveDir: process.cwd(), loader: "ts",
  },
  bundle: true, format: "esm", platform: "node", write: false, logLevel: "error",
});
const data = await import("data:text/javascript;base64," + Buffer.from(out.outputFiles[0].text).toString("base64"));
const { RICE_VARIETIES, CROP_GROUPS, FAMILY_GROUPS, CROP_CYCLES, PRICE_MONTHS, PRICE_SERIES } = data;
const forecasts = JSON.parse(readFileSync("src/data/generated/forecasts.json", "utf8"));

const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const groupId = (name) => name.toLowerCase();

const groups = [];
for (const [family, names] of Object.entries(FAMILY_GROUPS)) {
  for (const name of names) {
    const days = CROP_CYCLES.find(c => c.crop === name)?.days ?? null;
    groups.push({ id: groupId(name), name, family, days, sort: groups.length + 1 });
  }
}
const varieties = [
  ...RICE_VARIETIES.map(v => ({ ...v, group: "Rice" })),
  ...CROP_GROUPS.flatMap(g => g.varieties.map(v => ({ ...v, group: g.group }))),
];
const missing = varieties.filter(v => !groups.some(g => g.name === v.group));
if (missing.length) throw new Error("Varieties with no crop group: " + missing.map(v => v.name).join(", "));

// The price records: one row per recorded month, dated the 1st, with its
// move from the record before.
const records = [];
for (const [id, prices] of Object.entries(PRICE_SERIES)) {
  if (!varieties.some(v => v.id === id)) throw new Error(`Price records for an unknown variety: ${id}`);
  let before = null;
  prices.forEach((price, i) => {
    if (price === null) return;
    const change = before === null ? 0 : Math.round((price / before - 1) * 1000) / 10;
    records.push({ id, date: `${PRICE_MONTHS[i]}-01`, price, change });
    before = price;
  });
}
const sample = varieties.filter(v => !(v.id in PRICE_SERIES));

// The forecasts: every month each model looked ahead to.
const forecastRows = [];
for (const [id, c] of Object.entries(forecasts.crops)) {
  if (!varieties.some(v => v.id === id)) throw new Error(`Forecasts for an unknown variety: ${id}`);
  for (const model of ["arima", "lstm"]) {
    for (const p of c[model].forecast) {
      forecastRows.push({ id, model, month: `${p.month}-01`, price: p.price, low: p.lower, high: p.upper, mape: c[model].mape });
    }
  }
}

const achievements = [
  ["newbie", "Newbie", "Joined AniSense.", "auto", 1],
  ["first-harvest", "First harvest", "Posted a first harvest in the Market.", "auto", 2],
  ["first-sale", "First sale", "Made or recorded a first sale.", "auto", 3],
  ["farmer-of-the-week", "AniSense Farmer of the Week", "Featured to buyers as one of the week's best-rated farmers.", "auto", 4],
  ["farmer-of-the-month", "AniSense Farmer of the Month", "Top ratings and the most sales in a month.", "admin", 5],
  ["farmer-of-the-year", "AniSense Farmer of the Year", "AniSense's top farmer of the whole year.", "admin", 6],
];

const sql = `-- ═══════════════════════════════════════════════════════════════════════════
--  AniSense starter data  (run after schema.sql)
--
--  GENERATED by scripts/build-seed.mjs from the app's own data. To change it,
--  edit the source (src/data/crops.ts for crops, data/historical-prices.csv
--  for prices), run  node scripts/build-seed.mjs , and run this file again.
--  Safe to re-run: every row is added or brought up to date.
--
--  ${groups.length} crop groups · ${varieties.length} varieties · ${records.length} price records (${PRICE_MONTHS[0]} to ${PRICE_MONTHS[PRICE_MONTHS.length - 1]})
--  · ${sample.length} sample prices · ${forecastRows.length} forecasts · ${achievements.length} badges
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Crop groups ─────────────────────────────────────────────────────────────
insert into public.crop_groups (id, name, family, days_to_harvest, sort_order) values
${groups.map(g => `  (${q(g.id)}, ${q(g.name)}, ${q(g.family)}, ${g.days ?? "null"}, ${g.sort})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, family = excluded.family,
  days_to_harvest = excluded.days_to_harvest, sort_order = excluded.sort_order;

-- ─── Varieties ───────────────────────────────────────────────────────────────
insert into public.crops (id, group_id, name, sort_order) values
${varieties.map((v, i) => `  (${q(v.id)}, ${q(groupId(v.group))}, ${q(v.name)}, ${i + 1})`).join(",\n")}
on conflict (id) do update set
  group_id = excluded.group_id, name = excluded.name, sort_order = excluded.sort_order;

-- ─── Price records ───────────────────────────────────────────────────────────
-- The study's varieties: one row per recorded month, dated the 1st, from
-- data/historical-prices.csv. change_pct is the move from the record before.
-- The app shows the newest record of each variety as its price.
insert into public.crop_prices (crop_id, price_date, price_per_kg, change_pct) values
${records.map(r => `  (${q(r.id)}, ${q(r.date)}, ${r.price}, ${r.change})`).join(",\n")}
on conflict (crop_id, price_date) do update set
  price_per_kg = excluded.price_per_kg, change_pct = excluded.change_pct, is_sample = false;

-- ─── Sample prices ───────────────────────────────────────────────────────────
-- Varieties with no price records yet. These are SAMPLE numbers, not market
-- prices: replace them with real records before real farmers rely on them.
-- They are marked is_sample, so they are never drawn as price history.
insert into public.crop_prices (crop_id, price_date, price_per_kg, change_pct, is_sample) values
${sample.map(v => `  (${q(v.id)}, current_date, ${v.pricePerKg}, ${v.change}, true)`).join(",\n")}
on conflict (crop_id, price_date) do update set
  price_per_kg = excluded.price_per_kg, change_pct = excluded.change_pct, is_sample = true;

-- ─── Forecasts ───────────────────────────────────────────────────────────────
-- From ml/train_forecasts.py, trained on the records above on ${forecasts.generated}.
-- mape is the model's average miss, in %, on the ${forecasts.testMonths} months it was tested on.
insert into public.crop_forecasts (crop_id, model, target_month, price_per_kg, low_per_kg, high_per_kg, mape, generated_on) values
${forecastRows.map(f => `  (${q(f.id)}, ${q(f.model)}, ${q(f.month)}, ${f.price}, ${f.low}, ${f.high}, ${f.mape}, ${q(forecasts.generated)})`).join(",\n")}
on conflict (crop_id, model, target_month) do update set
  price_per_kg = excluded.price_per_kg, low_per_kg = excluded.low_per_kg, high_per_kg = excluded.high_per_kg,
  mape = excluded.mape, generated_on = excluded.generated_on;

-- ─── Badges ──────────────────────────────────────────────────────────────────
insert into public.achievements (id, name, description, awarded_by, sort_order) values
${achievements.map(a => `  (${a.slice(0, 4).map(q).join(", ")}, ${a[4]})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, description = excluded.description,
  awarded_by = excluded.awarded_by, sort_order = excluded.sort_order;
`;
writeFileSync("supabase/seed.sql", sql);
console.log(`supabase/seed.sql: ${groups.length} crop groups, ${varieties.length} varieties, ${records.length} price records, ${sample.length} sample prices, ${forecastRows.length} forecasts, ${achievements.length} badges`);
