// ─── node scripts/build-seed.mjs ──────────────────────────────────────────────
// Writes supabase/seed.sql from the app's own crop data, so the database's
// catalog and the app's can never drift apart:
//
//   crop_groups   the 10 crop types (src/data/crops.ts FAMILY_GROUPS, with
//                 days to harvest from src/data/cropCycles.ts)
//   crops         every variety (RICE_VARIETIES + CROP_GROUPS)
//   crop_prices   today's price for each variety
//   achievements  the badges
//
// Run it again after changing the crop data, then run seed.sql again in the
// SQL editor. Safe to re-run: every insert updates what is already there.

import { build } from "esbuild";
import { writeFileSync } from "node:fs";

// Load the app's TypeScript data files as a module.
const out = await build({
  stdin: {
    contents: `export { RICE_VARIETIES, CROP_GROUPS, FAMILY_GROUPS } from "./src/data/crops";
               export { CROP_CYCLES } from "./src/data/cropCycles";`,
    resolveDir: process.cwd(), loader: "ts",
  },
  bundle: true, format: "esm", platform: "node", write: false, logLevel: "error",
});
const data = await import("data:text/javascript;base64," + Buffer.from(out.outputFiles[0].text).toString("base64"));
const { RICE_VARIETIES, CROP_GROUPS, FAMILY_GROUPS, CROP_CYCLES } = data;

const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const groupId = (name) => name.toLowerCase();

const groups = [];
for (const [family, names] of Object.entries(FAMILY_GROUPS)) {
  for (const name of names) {
    const days = CROP_CYCLES.find(c => c.crop === name)?.days ?? null;
    groups.push({ id: groupId(name), name, family, days, sort: groups.length + 1 });
  }
}
const varieties = [
  ...RICE_VARIETIES.map(v => ({ ...v, group: "Rice" })),
  ...CROP_GROUPS.flatMap(g => g.varieties.map(v => ({ ...v, group: g.group }))),
];
const missing = varieties.filter(v => !groups.some(g => g.name === v.group));
if (missing.length) throw new Error("Varieties with no crop group: " + missing.map(v => v.name).join(", "));

const achievements = [
  ["newbie", "Newbie", "Joined AniSense.", "auto", 1],
  ["first-harvest", "First harvest", "Posted a first harvest in the Market.", "auto", 2],
  ["first-sale", "First sale", "Made or recorded a first sale.", "auto", 3],
  ["farmer-of-the-week", "AniSense Farmer of the Week", "Featured to buyers as one of the week's best-rated farmers.", "auto", 4],
  ["farmer-of-the-month", "AniSense Farmer of the Month", "Top ratings and the most sales in a month.", "admin", 5],
  ["farmer-of-the-year", "AniSense Farmer of the Year", "AniSense's top farmer of the whole year.", "admin", 6],
];

const sql = `-- ═══════════════════════════════════════════════════════════════════════════
--  AniSense starter data  (run after schema.sql)
--
--  GENERATED by scripts/build-seed.mjs from the app's own crop data. To change
--  it, edit src/data/crops.ts, run  node scripts/build-seed.mjs , and run this
--  file again. Safe to re-run: every row is added or brought up to date.
--
--  ${groups.length} crop groups · ${varieties.length} varieties · ${varieties.length} prices for today · ${achievements.length} badges
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Crop groups ─────────────────────────────────────────────────────────────
insert into public.crop_groups (id, name, family, days_to_harvest, sort_order) values
${groups.map(g => `  (${q(g.id)}, ${q(g.name)}, ${q(g.family)}, ${g.days ?? "null"}, ${g.sort})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, family = excluded.family,
  days_to_harvest = excluded.days_to_harvest, sort_order = excluded.sort_order;

-- ─── Varieties ───────────────────────────────────────────────────────────────
insert into public.crops (id, group_id, name, sort_order) values
${varieties.map((v, i) => `  (${q(v.id)}, ${q(groupId(v.group))}, ${q(v.name)}, ${i + 1})`).join(",\n")}
on conflict (id) do update set
  group_id = excluded.group_id, name = excluded.name, sort_order = excluded.sort_order;

-- ─── Today's prices ──────────────────────────────────────────────────────────
-- One row per variety for today. The admin adds a new day's prices the same
-- way (or in Table Editor → crop_prices); the app always shows the newest.
insert into public.crop_prices (crop_id, price_date, price_per_kg, change_pct) values
${varieties.map(v => `  (${q(v.id)}, current_date, ${v.pricePerKg}, ${v.change})`).join(",\n")}
on conflict (crop_id, price_date) do update set
  price_per_kg = excluded.price_per_kg, change_pct = excluded.change_pct;

-- ─── Badges ──────────────────────────────────────────────────────────────────
insert into public.achievements (id, name, description, awarded_by, sort_order) values
${achievements.map(a => `  (${a.slice(0, 4).map(q).join(", ")}, ${a[4]})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, description = excluded.description,
  awarded_by = excluded.awarded_by, sort_order = excluded.sort_order;
`;
writeFileSync("supabase/seed.sql", sql);
console.log(`supabase/seed.sql: ${groups.length} crop groups, ${varieties.length} varieties, ${varieties.length} prices, ${achievements.length} badges`);
